version: '3.1'

services:
  db:
    container_name: db_postgres
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fair-app
      POSTGRES_PASSWORD: fair@!20#
    restart: always
    ports:
      - 5432:5432
  rabbitmq:
    container_name: mq_rabbit
    image: bitnami/rabbitmq:latest
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
    ports:
      - 5672:5672
      - 15672:15672
  app:
    container_name: app_fair
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fair-app
      SPRING_DATASOURCE_USERNAME: fair-app
      SPRING_DATASOURCE_PASSWORD: fair@!20#
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on: 
      - db
      - rabbitmq
    ports:
      - 8080:8080