spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fair-app
    username: fair-app
    password: fair@!20#
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

aws:
  region: us-east-1
  bucketName: bucket-fair-app
  key: AKIAVOTQT4BJEDFLI4DE
  secret: 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

file:
  path: src\main\resources\files