spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market-app
    username: market-app
    password: market@!20#
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
