spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fair-app
    username: fair-app
    password: fair@!20#
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
    exchange: exd.fairapp
    queue: queue.fairapp
    routing-key: rk.fairapp

springdoc:
  api-docs:
    path: /api-docs

aws:
  region: us-east-1
  bucketName: bucket-fair-app
  key: AKIAVOTQT4BJEDFLI4DE
  secret: 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

file:
  path: src\main\resources\files