spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fair-app
    username: fair-app
    password: fair@!20#
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
